pipeline {
   agent any
   stages {
       stage ('Compile Stage') {
           steps {
                 sh './gradlew clean compile'
               }
           }
       }
        stage ('Build Stage') {
           steps {
               
                   sh './gradlew build'
               }
           }
   }
}
